Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.basic_1__types.
Require Import zoo.options.

Definition basic_1٠test1 : val :=
  0.

Definition basic_1٠test2 : val :=
  (-1).

Definition basic_1٠test3 : val :=
  basic_1٠test1.

Definition basic_1٠test4 : val :=
  (0, true).

Definition basic_1٠test5 : val :=
  (basic_1٠test2, basic_1٠test3).

Definition basic_1٠test6 : val :=
  §None.

Definition basic_1٠test7 : val :=
  ‘Some( 0 ).

Definition basic_1٠test8 : val :=
  ‘Some( fun: <> => () ).

Definition basic_1٠test9 : val :=
  ‘Some( §None ).

Definition basic_1٠test10 : val :=
  ‘Some( (‘Some( fun: <> => () ), ‘Some( () )) ).
