Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.basic_3__types.
Require Import zoo.options.

Definition basic_3٠test1 : val :=
  fun: "x1" "x2" =>
    "x1" + "x2".

Definition basic_3٠test2 : val :=
  fun: "x" <> =>
    "x".

Definition basic_3٠test3 : val :=
  fun: "x1" "x2" "x3" =>
    "x1" + "x2" + "x3".

Definition basic_3٠test4 : val :=
  fun: <> "x" <> =>
    "x".
