From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  basic_2__types.
From zoo Require Import
  options.

Definition basic_2٠test1 : val :=
  fun: "x" =>
    "x".

Definition basic_2٠test2 : val :=
  rec: "test2" "x" =>
    "x" + "test2" "x".

Definition basic_2٠test3 : val :=
  0.

Definition basic_2٠test4 : val :=
  1.

Definition basic_2٠test5 : val :=
  fun: "x" =>
    "x".

Definition basic_2٠test6 : val :=
  ().
