From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  basic_1__types.
From zoo Require Import
  options.

Definition basic_1_test1 : val :=
  0.

Definition basic_1_test2 : val :=
  (-1).

Definition basic_1_test3 : val :=
  basic_1_test1.

Definition basic_1_test4 : val :=
  (0, true).

Definition basic_1_test5 : val :=
  (basic_1_test2, basic_1_test3).

Definition basic_1_test6 : val :=
  §None.

Definition basic_1_test7 : val :=
  ‘Some( 0 ).

Definition basic_1_test8 : val :=
  ‘Some( fun: <> => () ).

Definition basic_1_test9 : val :=
  ‘Some( §None ).

Definition basic_1_test10 : val :=
  ‘Some( (‘Some( fun: <> => () ), ‘Some( () )) ).
