Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.basic_2__types.
Require Import zoo.options.

Definition basic_2٠test1 : val :=
  fun: "x" =>
    "x".

Definition basic_2٠test2 : val :=
  rec: "test2" "x" =>
    "x" + "test2" "x".

Definition basic_2٠test3 : val :=
  0.

Definition basic_2٠test4 : val :=
  1.

Definition basic_2٠test5 : val :=
  fun: "x" =>
    "x".

Definition basic_2٠test6 : val :=
  ().
