From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  function__types.
From zoo Require Import
  options.

Definition function٠test1 : val :=
  fun: "param" =>
    match: "param" with
    | [] =>
        ()
    | <> :: <> =>
        ()
    end.

Definition function٠test2 : val :=
  rec: "test2" "param" =>
    match: "param" with
    | [] =>
        ()
    | <> :: <> =>
        ()
    end.
