Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Definition function٠test1 : val :=
  𝗳𝘂𝗻 "param" ->
    𝗺𝗮𝘁𝗰𝗵 "param" 𝘄𝗶𝘁𝗵
    | [] ->
        ()
    | ⎽ :: ⎽ ->
        ()
    𝗲𝗻𝗱.

Definition function٠test2 : val :=
  𝗿𝗲𝗰 "test2" "param" ->
    𝗺𝗮𝘁𝗰𝗵 "param" 𝘄𝗶𝘁𝗵
    | [] ->
        ()
    | ⎽ :: ⎽ ->
        ()
    𝗲𝗻𝗱.
