Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.function__types.
Require Import zoo.options.

Definition function٠test1 : val :=
  fun: "param" =>
    match: "param" with
    | [] =>
        ()
    | <> :: <> =>
        ()
    end.

Definition function٠test2 : val :=
  rec: "test2" "param" =>
    match: "param" with
    | [] =>
        ()
    | <> :: <> =>
        ()
    end.
