Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'generative_2٠A'" := (
  in_type "tests.generative_2.t" 0
)(in custom zoo_tag
).
Notation "'generative_2٠B'" := (
  in_type "tests.generative_2.t" 1
)(in custom zoo_tag
).

Definition generative_2٠test : val :=
  𝗳𝘂𝗻 ⎽ ->
    ‘generative_2٠A@[ () ] ⍮
    ‘generative_2٠B( () ) ⍮
    ().
