Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'generative_1٠A'" := (
  in_type "tests.generative_1.t" 0
)(in custom zoo_tag
).
Notation "'generative_1٠B'" := (
  in_type "tests.generative_1.t" 1
)(in custom zoo_tag
).

Definition generative_1٠test : val :=
  𝗳𝘂𝗻 ⎽ ->
    ‘generative_1٠A[ () ] ⍮
    ‘generative_1٠B( () ) ⍮
    ().
