Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.if__types.
Require Import zoo.options.

Definition if٠test1 : val :=
  fun: "b" =>
    if: "b" then (
      0
    ) else (
      1
    ).

Definition if٠test2 : val :=
  fun: "b0" "b1" =>
    if: "b0" then (
      0
    ) else if: "b1" then (
      1
    ) else (
      2
    ).

Definition if٠test3 : val :=
  fun: "b0" "b1" "b2" =>
    if: "b0" then (
      0
    ) else if: "b1" then (
      1
    ) else if: "b2" then (
      2
    ) else (
      3
    ).
