Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.labeled_arguments__types.
Require Import zoo.options.

Definition labeled_arguments٠test1 : val :=
  fun: "x1" "x2" "x3" "x4" =>
    "x1" ;;
    "x2" ;;
    "x3" ;;
    "x4" ;;
    ().

Definition labeled_arguments٠test2 : val :=
  fun: "x1" <> "x3" "x4" =>
    "x1" ;;
    "x3" ;;
    "x4" ;;
    ().

Definition labeled_arguments٠test3 : val :=
  fun: <> =>
    labeled_arguments٠test1 1 2 3 4.
