Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.list__types.
Require Import zoo.options.

Definition list٠test1 : val :=
  𝗳𝘂𝗻 ⎽ ->
    [] ⍮
    0 :: [] ⍮
    1 :: [] ⍮
    ().

Definition list٠test2 : val :=
  𝗳𝘂𝗻 "xs" ->
    𝗺𝗮𝘁𝗰𝗵 "xs" 𝘄𝗶𝘁𝗵
    | [] ->
        ()
    | "x" :: "xs" ->
        "x" ⍮
        "xs" ⍮
        ()
    𝗲𝗻𝗱.
