Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.list__types.
Require Import zoo.options.

Definition list٠test1 : val :=
  fun: <> =>
    [] ;;
    0 :: [] ;;
    1 :: [] ;;
    ().

Definition list٠test2 : val :=
  fun: "xs" =>
    match: "xs" with
    | [] =>
        ()
    | "x" :: "xs" =>
        "x" ;;
        "xs" ;;
        ()
    end.
