From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  list__types.
From zoo Require Import
  options.

Definition list٠test1 : val :=
  fun: <> =>
    [] ;;
    0 :: [] ;;
    1 :: [] ;;
    ().

Definition list٠test2 : val :=
  fun: "xs" =>
    match: "xs" with
    | [] =>
        ()
    | "x" :: "xs" =>
        "x" ;;
        "xs" ;;
        ()
    end.
