Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.mutual__types.
Require Import zoo.options.

#[local] Definition __zoo_recs_0 :=
  ( recs: "test3" "x" =>
      "x"
    and: "test4" "x" =>
      "x"
  )%zoo_recs.
Definition mutual٠test3 :=
  ValRecs 0 __zoo_recs_0.
Definition mutual٠test4 :=
  ValRecs 1 __zoo_recs_0.
#[global] Instance :
  AsValRecs' mutual٠test3 0 __zoo_recs_0 [
    mutual٠test3 ;
    mutual٠test4
  ].
Proof.
  done.
Qed.
#[global] Instance :
  AsValRecs' mutual٠test4 1 __zoo_recs_0 [
    mutual٠test3 ;
    mutual٠test4
  ].
Proof.
  done.
Qed.

#[local] Definition __zoo_recs_1 :=
  ( recs: "test5" "x" =>
      "test6" "x"
    and: "test6" "x" =>
      "test5" "x"
  )%zoo_recs.
Definition mutual٠test5 :=
  ValRecs 0 __zoo_recs_1.
Definition mutual٠test6 :=
  ValRecs 1 __zoo_recs_1.
#[global] Instance :
  AsValRecs' mutual٠test5 0 __zoo_recs_1 [
    mutual٠test5 ;
    mutual٠test6
  ].
Proof.
  done.
Qed.
#[global] Instance :
  AsValRecs' mutual٠test6 1 __zoo_recs_1 [
    mutual٠test5 ;
    mutual٠test6
  ].
Proof.
  done.
Qed.
