Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.operators_1__types.
Require Import zoo.options.

Definition operators_1٠test1 : val :=
  fun: "i" =>
    ~ true ;;
    - "i" ;;
    "i" + "i" ;;
    "i" - "i" ;;
    "i" * "i" ;;
    "i" `quot` "i" ;;
    "i" `rem` "i" ;;
    "i" `land` "i" ;;
    "i" `lor` "i" ;;
    "i" `lsl` "i" ;;
    "i" `lsr` "i" ;;
    "i" == "i" ;;
    "i" != "i" ;;
    "i" ≤ "i" ;;
    "i" < "i" ;;
    "i" ≥ "i" ;;
    "i" > "i" ;;
    2 * "i" + ("i" + 1) < "i" ;;
    true and true ;;
    true or true ;;
    true and true or true ;;
    true and (true or true) ;;
    true or true and true ;;
    (true or true) and true ;;
    ().

Definition operators_1٠test2 : val :=
  fun: "i" =>
    (fun: "1" "2" => "1" + "2") ;;
    (fun: "1" "2" => "1" + "2") "i" ;;
    "i" + "i" ;;
    ().
