Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.proph__types.
Require Import zoo.options.

Definition proph٠test1 : val :=
  fun: <> =>
    let: "proph" := Proph in
    Resolve (1 + 1) "proph" ().

Definition proph٠test2 : val :=
  fun: <> =>
    let: "proph" := Proph in
    Resolve Skip "proph" ().

Definition proph٠test3 : val :=
  fun: <> =>
    let: "proph" := Proph in
    let: "@tmp" := () in
    Resolve Skip "proph" "@tmp" ;;
    "@tmp".
