From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From zoo_std Require Import
  diverge.
From tests Require Import
  raise_1__types.
From zoo Require Import
  options.

Definition raise_1٠test1 : val :=
  fun: <> =>
    diverge ().

Definition raise_1٠test2 : val :=
  fun: <> =>
    diverge ().

Definition raise_1٠test3 : val :=
  fun: <> =>
    diverge ().
