From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From zoo_std Require Import
  assume.
From tests Require Import
  raise_2__types.
From zoo Require Import
  options.

Definition raise_2٠test1 : val :=
  fun: "b" =>
    assume "b".

Definition raise_2٠test2 : val :=
  fun: "b" =>
    assume "b".

Definition raise_2٠test3 : val :=
  fun: "b" =>
    assume "b".
