Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.record_2__types.
Require Import zoo.options.

Definition record_2٠test1 : val :=
  fun: <> =>
    let: "t2" := (0, 1) in
    "t2".<f1>.

Definition record_2٠test2 : val :=
  fun: "t" =>
    let: "f1", "f2" := "t" in
    "f1" + "f2".

Definition record_2٠test3 : val :=
  fun: "t" =>
    (0, "t".<f2>).

Definition record_2٠test4 : val :=
  fun: <> =>
    let: "@tmp" := (0, 0) in
    (0, "@tmp".<f2>).
