Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.record_1__types.
Require Import zoo.options.

Definition record_1٠test1 : val :=
  fun: <> =>
    let: "t1" := { 0, 1 } in
    "t1".{f1} ;;
    "t1" <-{f1} 0.

Definition record_1٠test2 : val :=
  fun: "t" =>
    { 0, "t".{f2} }.

Definition record_1٠test3 : val :=
  fun: <> =>
    let: "@tmp" := { 0, 0 } in
    { 0, "@tmp".{f2} }.
