Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.record_1__types.
Require Import zoo.options.

Definition record_1٠test1 : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗹𝗲𝘁 "t1" = { 0, 1 } 𝗶𝗻
    "t1".{f1} ⍮
    "t1" <-{f1} 0.

Definition record_1٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    { 0, "t".{f2} }.

Definition record_1٠test3 : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗹𝗲𝘁 "@tmp" = { 0, 0 } 𝗶𝗻
    { 0, "@tmp".{f2} }.
