From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  record_2__types.
From zoo Require Import
  options.

Definition record_2_test1 : val :=
  fun: <> =>
    let: "t2" := (#0, #1) in
    "t2".<f1>.

Definition record_2_test2 : val :=
  fun: "t" =>
    let: "f1", "f2" := "t" in
    "f1" + "f2".

Definition record_2_test3 : val :=
  fun: "t" =>
    (#0, "t".<f2>).

Definition record_2_test4 : val :=
  fun: <> =>
    let: "@tmp" := (#0, #0) in
    (#0, "@tmp".<f2>).
