Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.record_2__types.
Require Import zoo.options.

Definition record_2٠test1 : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗹𝗲𝘁 "t2" = (0, 1) 𝗶𝗻
    "t2".<f1>.

Definition record_2٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗹𝗲𝘁 "f1", "f2" = "t" 𝗶𝗻
    "f1" + "f2".

Definition record_2٠test3 : val :=
  𝗳𝘂𝗻 "t" ->
    (0, "t".<f2>).

Definition record_2٠test4 : val :=
  𝗳𝘂𝗻 ⎽ ->
    𝗹𝗲𝘁 "@tmp" = (0, 0) 𝗶𝗻
    (0, "@tmp".<f2>).
