Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.unboxed_record__types.
Require Import zoo.options.

Definition unboxed_record٠test1 : val :=
  fun: "x" =>
    "x".

Definition unboxed_record٠test2 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "x" =>
        "x"
    end.

Definition unboxed_record٠test3 : val :=
  fun: "t" =>
    let: "x" := "t" in
    "x".
