From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From tests Require Import
  unboxed_variant__types.
From zoo Require Import
  options.

Definition unboxed_variant٠test1 : val :=
  fun: "x" =>
    "x".

Definition unboxed_variant٠test2 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "x" =>
        "x"
    end.

Definition unboxed_variant٠test3 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "x" =>
        "x"
    end.
