Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.unboxed_variant__types.
Require Import zoo.options.

Definition unboxed_variant٠test1 : val :=
  𝗳𝘂𝗻 "x" ->
    "x".

Definition unboxed_variant٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | ⎽ 𝗮𝘀 "x" ->
        "x"
    𝗲𝗻𝗱.

Definition unboxed_variant٠test3 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | ⎽ 𝗮𝘀 "x" ->
        "x"
    𝗲𝗻𝗱.
