Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.variant_4__types.
Require Import zoo.options.

Definition variant_4٠test1 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        0
    | B ⎽ ⎽ 𝗮𝘀 "r" ->
        "r".{f1}
    𝗲𝗻𝗱.

Definition variant_4٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        0
    | B ⎽ ⎽ 𝗮𝘀 "t" ->
        𝗹𝗲𝘁 "r" = "t" 𝗶𝗻
        "t" ⍮
        "r".{f1}
    𝗲𝗻𝗱.

Definition variant_4٠test3 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        §A
    | B ⎽ ⎽ 𝗮𝘀 "r" ->
        "r"
    𝗲𝗻𝗱.

Definition variant_4٠test4 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        §A
    | B ⎽ ⎽ 𝗮𝘀 "t" ->
        𝗹𝗲𝘁 "r" = "t" 𝗶𝗻
        "t" ⍮
        "r"
    𝗲𝗻𝗱.
