Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'variant_4٠A'" := (
  in_type "tests.variant_4.t" 0
)(in custom zoo_tag
).
Notation "'variant_4٠B'" := (
  in_type "tests.variant_4.t" 1
)(in custom zoo_tag
).

Notation "'variant_4٠f1'" := (
  in_type "tests.variant_4.t.B" 0
)(in custom zoo_field
).
Notation "'variant_4٠f2'" := (
  in_type "tests.variant_4.t.B" 1
)(in custom zoo_field
).

Definition variant_4٠test1 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | variant_4٠A ->
        0
    | variant_4٠B ⎽ ⎽ 𝗮𝘀 "r" ->
        "r".{variant_4٠f1}
    𝗲𝗻𝗱.

Definition variant_4٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | variant_4٠A ->
        0
    | variant_4٠B ⎽ ⎽ 𝗮𝘀 "t" ->
        𝗹𝗲𝘁 "r" = "t" 𝗶𝗻
        "t" ⍮
        "r".{variant_4٠f1}
    𝗲𝗻𝗱.

Definition variant_4٠test3 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | variant_4٠A ->
        §variant_4٠A
    | variant_4٠B ⎽ ⎽ 𝗮𝘀 "r" ->
        "r"
    𝗲𝗻𝗱.

Definition variant_4٠test4 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | variant_4٠A ->
        §variant_4٠A
    | variant_4٠B ⎽ ⎽ 𝗮𝘀 "t" ->
        𝗹𝗲𝘁 "r" = "t" 𝗶𝗻
        "t" ⍮
        "r"
    𝗲𝗻𝗱.
