Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.variant_1__types.
Require Import zoo.options.

Definition variant_1٠test1 : val :=
  𝗳𝘂𝗻 ⎽ ->
    §A ⍮
    ‘B( 0 ) ⍮
    ‘C( 0, 0 ) ⍮
    ().

Definition variant_1٠test2 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        0
    | B "i" ->
        "i"
    | C "i1" "i2" ->
        "i1" + "i2"
    𝗲𝗻𝗱.

Definition variant_1٠test3 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        ()
    | B ⎽ ->
        ()
    | C ⎽ ⎽ ->
        ()
    𝗲𝗻𝗱.

Definition variant_1٠test4 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        §A
    | B ⎽ 𝗮𝘀 "t" ->
        "t"
    | C ⎽ ⎽ 𝗮𝘀 "t" ->
        "t"
    𝗲𝗻𝗱.

Definition variant_1٠test5 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        ()
    | ⎽ ->
        ()
    𝗲𝗻𝗱.

Definition variant_1٠test6 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | ⎽ 𝗮𝘀 "t" ->
        "t"
    𝗲𝗻𝗱.

Definition variant_1٠test7 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | ⎽ 𝗮𝘀 "t" ->
        𝗹𝗲𝘁 "t'" = "t" 𝗶𝗻
        "t" ⍮
        "t'"
    𝗲𝗻𝗱.

Definition variant_1٠test8 : val :=
  𝗳𝘂𝗻 "t" ->
    𝗺𝗮𝘁𝗰𝗵 "t" 𝘄𝗶𝘁𝗵
    | A ->
        ()
    | B ⎽ ->
        ()
    | C ⎽ ⎽ ->
        ()
    𝗲𝗻𝗱.
