Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'A'" := (
  in_type "tests.variant_4.t" 0
)(in custom zoo_tag
).
Notation "'B'" := (
  in_type "tests.variant_4.t" 1
)(in custom zoo_tag
).

Notation "'f1'" := (
  in_type "tests.variant_4.t.B" 0
)(in custom zoo_field
).
Notation "'f2'" := (
  in_type "tests.variant_4.t.B" 1
)(in custom zoo_field
).
