Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.variant_1__types.
Require Import zoo.options.

Definition variant_1٠test1 : val :=
  fun: <> =>
    §A ;;
    ‘B( 0 ) ;;
    ‘C( 0, 0 ) ;;
    ().

Definition variant_1٠test2 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B "i" =>
        "i"
    | C "i1" "i2" =>
        "i1" + "i2"
    end.

Definition variant_1٠test3 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        ()
    | B <> =>
        ()
    | C <> <> =>
        ()
    end.

Definition variant_1٠test4 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        §A
    | B <> as "t" =>
        "t"
    | C <> <> as "t" =>
        "t"
    end.

Definition variant_1٠test5 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        ()
    |_ =>
        ()
    end.

Definition variant_1٠test6 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "t" =>
        "t"
    end.

Definition variant_1٠test7 : val :=
  fun: "t" =>
    match: "t" with
    |_ as "t" =>
        let: "t'" := "t" in
        "t" ;;
        "t'"
    end.

Definition variant_1٠test8 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        ()
    | B <> =>
        ()
    | C <> <> =>
        ()
    end.
