Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.variant_4__types.
Require Import zoo.options.

Definition variant_4٠test1 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B <> <> as "r" =>
        "r".{f1}
    end.

Definition variant_4٠test2 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B <> <> as "t" =>
        let: "r" := "t" in
        "t" ;;
        "r".{f1}
    end.

Definition variant_4٠test3 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        §A
    | B <> <> as "r" =>
        "r"
    end.

Definition variant_4٠test4 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        §A
    | B <> <> as "t" =>
        let: "r" := "t" in
        "t" ;;
        "r"
    end.
