From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From zoo Require Import
  options.

Notation "'A'" := (
  in_type "tests.variant_3.t" 0
)(in custom zoo_tag
).
Notation "'B'" := (
  in_type "tests.variant_3.t" 1
)(in custom zoo_tag
).

Notation "'f1'" := (
  in_type "tests.variant_3.t.B" 0
)(in custom zoo_proj
).
Notation "'f2'" := (
  in_type "tests.variant_3.t.B" 1
)(in custom zoo_proj
).
