Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import tests.variant_3__types.
Require Import zoo.options.

Definition variant_3٠test1 : val :=
  fun: <> =>
    ‘B( 0, 0 ).

Definition variant_3٠test2 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B "f1" "f2" =>
        "f1" + "f2"
    end.

Definition variant_3٠test3 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B "f1" "f2" as "t" =>
        "t" ;;
        "f1" + "f2"
    end.

Definition variant_3٠test4 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B "x1" "x2" =>
        "x1" + "x2"
    end.

Definition variant_3٠test5 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B "x1" "x2" as "t" =>
        "t" ;;
        "x1" + "x2"
    end.

Definition variant_3٠test6 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B <> <> as "r" =>
        "r".<f1> + "r".<f2>
    end.

Definition variant_3٠test7 : val :=
  fun: "t" =>
    match: "t" with
    | A =>
        0
    | B <> <> as "t" =>
        let: "r" := "t" in
        "t" ;;
        "r".<f1> + "r".<f2>
    end.
