Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import zoo.options.

Notation "'f1'" := (
  in_type "tests.zoo_force_record.t1" 0
)(in custom zoo_field
).
Notation "'f2'" := (
  in_type "tests.zoo_force_record.t1" 1
)(in custom zoo_field
).

Notation "'A'" := (
  in_type "tests.zoo_force_record.t2" 0
)(in custom zoo_tag
).
Notation "'B'" := (
  in_type "tests.zoo_force_record.t2" 1
)(in custom zoo_tag
).

Notation "'f'" := (
  in_type "tests.zoo_force_record.t2.B" 0
)(in custom zoo_field
).
