From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From foo Require Import
  bar.
From tests Require Import
  zoo_overwrite__types.
From zoo Require Import
  options.

Definition zoo_overwrite_test1 : val :=
  fun: <> =>
    ().

Definition zoo_overwrite_test2 : val :=
  rec: "test2" <> =>
    "test2" ().

Definition zoo_overwrite_test3 : val :=
  raw.

Definition zoo_overwrite_test4 : val :=
  raw.
