Require Import zoo.prelude.
Require Import zoo.language.typeclasses.
Require Import zoo.language.notations.
Require Import foo.bar.
Require Import tests.zoo_overwrite__types.
Require Import zoo.options.

Definition zoo_overwrite٠test1 : val :=
  fun: <> =>
    ().

Definition zoo_overwrite٠test2 : val :=
  rec: "test2" <> =>
    "test2" ().

Definition zoo_overwrite٠test3 : val :=
  bar٠raw.

Definition zoo_overwrite٠test4 : val :=
  bar٠raw.
