From zoo Require Import
  prelude.
From zoo.language Require Import
  typeclasses
  notations.
From foo Require Import
  bar.
From tests Require Import
  zoo_overwrite__types.
From zoo Require Import
  options.

Definition zoo_overwrite٠test1 : val :=
  fun: <> =>
    ().

Definition zoo_overwrite٠test2 : val :=
  rec: "test2" <> =>
    "test2" ().

Definition zoo_overwrite٠test3 : val :=
  bar٠raw.

Definition zoo_overwrite٠test4 : val :=
  bar٠raw.
